#!/usr/bin/env python3
"""Render the CALIBER Cookbooks as NATIVE doc-suite pages.

Produces, in ../../docs-site/:
  • m-16-cookbooks.html              — the index (a card per cookbook)
  • m-cookbook-<nn>-<slug>.html      — one self-contained detail page per cookbook
  • cookbooks-nav.json               — {href,label} manifest consumed by build-docs.mjs
and appends cookbook component CSS to docs.css.

Each detail page is fully self-contained for in-app serving:
  • every UI step gets an auto-generated UI **snapshot** (derived from its nav
    path + fields + button),
  • asset files are **inlined** as copyable code blocks with same-page anchors,
    so there are no cross-folder links that 404 when served at /caliber/docs/.

Mermaid + theme come from the doc-suite (docs.css / docs.js / mermaid@11).

    python3 build.py
"""
from __future__ import annotations

import html
import json
import pathlib
import re

from content import COOKBOOKS, INTRO, TRACKS  # noqa: E402

HERE = pathlib.Path(__file__).resolve().parent   # docs-site/cookbooks/training
COOKBOOKS_DIR = HERE.parent                       # docs-site/cookbooks
DOCS_SITE = HERE.parents[1]                        # docs-site (the published site)
DOCS_CSS = DOCS_SITE / "docs.css"
NAV_JSON = DOCS_SITE / "cookbooks-nav.json"
INDEX_OUT = DOCS_SITE / "m-16-cookbooks.html"
CSS_MARKER = "/* === cookbooks training (generated by cookbooks/training/build.py) === */"
BRAND_SHORT = "CALIBER"
BRAND_FULL = "CALIBER : Contextual Adaptive Lifecycle for Intelligent Build, Evaluation, and Refinement"
DOCS_HOME_LABEL = f"{BRAND_FULL} docs home"

NAV_ITEMS = [
    "Dashboard", "Workflows", "Plans", "Prompts", "Tools", "Skills",
    "MCP Servers", "Knowledge Base", "Object Store", "Test Sets", "Judges",
    "Evaluations", "Observability", "Review Queues", "Settings",
]
# breadcrumb token (lower) -> sidebar nav item
NAV_ALIASES = {
    "prompts": "Prompts", "tools": "Tools", "skills": "Skills",
    "mcp servers": "MCP Servers", "mcp": "MCP Servers",
    "knowledge base": "Knowledge Base", "knowledge": "Knowledge Base",
    "object store": "Object Store", "test sets": "Test Sets", "test set": "Test Sets",
    "judges": "Judges", "evaluations": "Evaluations", "observability": "Observability",
    "review queues": "Review Queues", "review queue": "Review Queues",
    "workflows": "Workflows", "plans": "Plans", "aria plans": "Plans",
    "settings": "Settings", "dashboard": "Dashboard",
}


def esc(value: object) -> str:
    return html.escape(str(value), quote=True)


def strip_tags(s: str) -> str:
    return re.sub(r"\s+", " ", re.sub(r"<[^>]+>", "", str(s))).strip()


def slugify(s: str) -> str:
    return re.sub(r"-+", "-", re.sub(r"[^a-z0-9]+", "-", str(s).lower())).strip("-")


def folder_for(num: str) -> pathlib.Path | None:
    for d in sorted(COOKBOOKS_DIR.iterdir()):
        if d.is_dir() and d.name.startswith(num + "-"):
            return d
    return None


def detail_filename(cb: dict) -> str:
    return f"m-cookbook-{cb['num']}-{cb['slug']}.html"


def steps_for(cb: dict) -> list[dict]:
    folder = folder_for(cb["num"])
    if folder:
        override = folder / "training-steps.json"
        if override.exists():
            try:
                data = json.loads(override.read_text(encoding="utf-8"))
                if isinstance(data, dict) and data.get("steps"):
                    return data["steps"]
            except Exception:  # noqa: BLE001
                pass
    return cb.get("steps", [])


def badge(text: str, kind: str = "") -> str:
    return f'<span class="ck-badge{(" ck-" + kind) if kind else ""}">{esc(text)}</span>'


# ── per-step UI snapshot ───────────────────────────────────────────────────
def nav_active_for(where: str) -> str:
    segs = [s.strip().lower() for s in str(where).split("›")]
    for seg in segs:
        if seg in NAV_ALIASES:
            return NAV_ALIASES[seg]
    for seg in segs:  # loose contains match
        for token, item in NAV_ALIASES.items():
            if token in seg:
                return item
    return ""


def step_mock(step: dict) -> str:
    """A compact, focused snapshot of the relevant CALIBER screen for one step:
    browser chrome + breadcrumb + page chip + the form panel (fields + button).
    Deliberately lightweight (no full app sidebar) so it reads as a clean shot."""
    where = step.get("where", "")
    active = nav_active_for(where)
    tail = [s.strip() for s in str(where).split("›") if s.strip()]
    title = tail[-1] if tail else "CALIBER"
    crumb = " › ".join(tail) if tail else "CALIBER"
    page_chip = f'<span class="ck-mk-page">{esc(active)}</span>' if active else ""
    fields_html = ""
    for f in step.get("fill", [])[:5]:
        val = strip_tags(f[1])
        if len(val) > 84:
            val = val[:84] + "…"
        fields_html += (
            f'<label class="ck-mk-field"><span class="ck-mk-label">{esc(strip_tags(f[0]))}</span>'
            f'<span class="ck-mk-input">{esc(val) or "&nbsp;"}</span></label>'
        )
    clicks = step.get("click")
    clicks = clicks if isinstance(clicks, list) else ([clicks] if clicks else [])
    buttons_html = "".join(
        f'<span class="ck-mk-btn{" ghost" if i else ""}">{esc(b)}</span>' for i, b in enumerate(clicks)
    )
    if not fields_html and not buttons_html:
        fields_html = '<div class="ck-mk-empty">Read / inspect this surface — no form to fill.</div>'
    actions = f'<div class="ck-mk-actions">{buttons_html}</div>' if buttons_html else ""
    return f"""<figure class="ck-mock" aria-label="CALIBER UI snapshot">
      <div class="ck-mk-chrome"><span class="ck-mk-dot"></span><span class="ck-mk-dot"></span><span class="ck-mk-dot"></span>
        <span class="ck-mk-url">caliber · {esc(crumb)}</span></div>
      <div class="ck-mk-screen">
        <div class="ck-mk-bar">{page_chip}<span class="ck-mk-title">{esc(title)}</span></div>
        <div class="ck-mk-panel">{fields_html}{actions}</div>
      </div>
    </figure>"""


# ── inlined assets (no cross-folder links — same-page anchors) ─────────────
LANGS = {".md": "markdown", ".json": "json", ".jsonl": "json", ".py": "python",
         ".yaml": "yaml", ".yml": "yaml", ".csv": "csv", ".txt": "text"}
MAX_ASSET = 12000


def resolve_asset(folder: pathlib.Path, href: str) -> pathlib.Path | None:
    # hrefs look like ../cookbooks/<folder>/assets/<path>
    m = re.search(r"assets/.+$", href)
    if not m:
        return None
    p = folder / m.group(0)
    return p if p.exists() and p.is_file() else None


_CB_HREF = re.compile(r"\.\./cookbooks/[^\"'#\s]+?/assets/[^\"'#\s]+")


def gather_assets(cb: dict, folder: pathlib.Path) -> tuple[list[dict], dict]:
    """Scan every cookbook href (structured assetlink + inline links in do/fill)
    for ``../cookbooks/<folder>/assets/<path>``; return (ordered unique asset
    blocks, href→asset map). Anything resolvable is inlined + linked by anchor."""
    href_map: dict[str, dict] = {}
    order: list[dict] = []
    seen: set[str] = set()

    def consider(href: str) -> None:
        href = (href or "").strip()
        if not href or href in href_map:
            return
        path = resolve_asset(folder, href)
        if not path:
            return
        rel = str(path.relative_to(folder))
        slug = "asset-" + slugify(rel)
        rec = {"slug": slug, "rel": rel, "label": path.name, "path": path}
        href_map[href] = rec
        if slug not in seen:
            seen.add(slug)
            order.append(rec)

    for step in steps_for(cb):
        links = step.get("assetlink") or []
        if isinstance(links, dict):
            links = [links]
        for a in links:
            consider(a.get("href", ""))
        blob = str(step.get("do", "")) + " " + " ".join(str(f[1]) for f in step.get("fill", []))
        for href in _CB_HREF.findall(blob):
            consider(href)
    return order, href_map


def rewrite_links(text: str, href_map: dict) -> str:
    """Point every inline ../cookbooks asset href at its same-page anchor; unwrap
    any leftover (unresolvable) cookbook anchors so no link can 404 in-app."""
    for href, rec in href_map.items():
        text = text.replace(f'href="{href}"', f'href="#{rec["slug"]}"')
    return re.sub(r'<a\b[^>]*href="\.\./cookbooks/[^"]*"[^>]*>(.*?)</a>', r"\1", text, flags=re.S)


def render_asset_block(a: dict) -> str:
    try:
        text = a["path"].read_text(encoding="utf-8")
    except Exception:  # noqa: BLE001
        text = "(could not read file)"
    truncated = ""
    if len(text) > MAX_ASSET:
        text = text[:MAX_ASSET]
        truncated = '<div class="ck-asset-trunc">… truncated — open the file in the repo for the full content.</div>'
    lang = LANGS.get(a["path"].suffix, "text")
    return f"""<div class="ck-asset" id="{esc(a['slug'])}">
      <div class="ck-asset-bar"><span class="ck-asset-name">{esc(a['rel'])}</span>
        <button type="button" class="ck-copy" data-ck-copy>Copy</button></div>
      <pre data-lang="{esc(lang)}"><code>{esc(text)}</code></pre>{truncated}
    </div>"""


# ── step list ──────────────────────────────────────────────────────────────
def render_steps(cb: dict, folder: pathlib.Path, href_map: dict) -> str:
    out = ['<ol class="ck-steps">']
    for s in steps_for(cb):
        where = f'<code class="ck-where">{esc(s["where"])}</code>' if s.get("where") else ""
        chips = ""
        if s.get("asset"):
            chips += f'<span class="ck-made">creates · {esc(s["asset"])}</span>'
        links = s.get("assetlink") or []
        if isinstance(links, dict):
            links = [links]
        for a in links:
            rec = href_map.get((a.get("href") or "").strip())
            if rec:
                chips += f' <a class="ck-assetref" href="#{esc(rec["slug"])}">{esc(a.get("label") or rec["label"])} ↓</a>'
        head = f'<div class="ck-step-head">{where}{(" " + chips) if chips else ""}</div>'
        do = f'<div class="ck-step-do">{rewrite_links(str(s["do"]), href_map)}</div>' if s.get("do") else ""
        fill = ""
        if s.get("fill"):
            rows = "".join(
                f"<tr><td>{esc(strip_tags(f[0]))}</td><td>{rewrite_links(str(f[1]), href_map)}</td></tr>"
                for f in s["fill"]
            )
            fill = f'<div class="ck-fill"><div class="ck-fill-t">Fill in</div><table><tbody>{rows}</tbody></table></div>'
        click = ""
        if s.get("click"):
            btns = s["click"] if isinstance(s["click"], list) else [s["click"]]
            click = '<div class="ck-click">Click ' + " then ".join(
                f'<span class="ck-btn">{esc(b)}</span>' for b in btns) + "</div>"
        see = f'<div class="ck-see"><strong>You\'ll see:</strong> {s["see"]}</div>' if s.get("see") else ""
        out.append(
            f'<li><div class="ck-step-grid"><div class="ck-step-text">{head}{do}{fill}{click}{see}</div>'
            f'<div class="ck-step-snap"><div class="ck-snap-label">Screen snapshot</div>{step_mock(s)}</div></div></li>'
        )
    out.append("</ol>")
    return "".join(out)


def render_table(rows: list[dict], cols: list[tuple[str, str]]) -> str:
    head = "".join(f"<th>{esc(label)}</th>" for label, _ in cols)
    body = "".join("<tr>" + "".join(f"<td>{r.get(k,'')}</td>" for _, k in cols) + "</tr>" for r in rows)
    return f'<div class="table-wrap"><table><thead><tr>{head}</tr></thead><tbody>{body}</tbody></table></div>'


# ── pages ────────────────────────────────────────────────────────────────--
def render_detail_body(cb: dict, prev_cb: dict | None, next_cb: dict | None) -> str:
    folder = folder_for(cb["num"])
    badges = badge(cb["track"], "track") + badge(cb["level"], "ok") + badge(cb["time"], "orange")
    surfaces = " ".join(badge(s, "surface") for s in cb.get("surfaces", []))
    learn = "".join(f"<li>{x}</li>" for x in cb.get("learn", []))
    order, href_map = gather_assets(cb, folder) if folder else ([], {})
    assets_inline = "".join(render_asset_block(a) for a in order)
    gates_tbl = render_table(cb.get("gates", []), [("Quality gate", "gate"), ("Target", "target")])
    notes = "".join(f"<li>{n}</li>" for n in cb.get("notes", []))
    pager = '<nav class="ck-pager">'
    pager += f'<a href="{detail_filename(prev_cb)}">← {esc(prev_cb["title"])}</a>' if prev_cb else "<span></span>"
    pager += '<a class="ck-pager-up" href="m-16-cookbooks.html">All cookbooks</a>'
    pager += f'<a href="{detail_filename(next_cb)}">{esc(next_cb["title"])} →</a>' if next_cb else "<span></span>"
    pager += "</nav>"
    assets_section = (
        f'<h2 id="assets">Assets (copy-paste)</h2>'
        f'<p class="ck-assets-lead">The exact files this cookbook uses — copy each into the matching field. '
        f'Source: <code>docs-site/cookbooks/{esc(folder.name)}/assets/</code>.</p>{assets_inline}'
        if order else ""
    )
    return f"""
      <nav class="doc-breadcrumb" aria-label="Breadcrumb">
        <span>Cookbooks</span><span aria-hidden="true">/</span>
        <a href="m-16-cookbooks.html">All</a><span aria-hidden="true">/</span>
        <span class="current">{esc(cb['num'])} · {esc(cb['title'])}</span>
      </nav>
      <header class="doc-header">
        <p class="doc-eyebrow">Cookbook {esc(cb['num'])} · {esc(cb['track'])}</p>
        <h1>{esc(cb['title'])}</h1>
        <p class="doc-lead">{esc(cb['subtitle'])}</p>
        <div class="ck-badges">{badges}</div>
      </header>
      <div class="ck-cols">
        <div class="callout"><strong>What you build.</strong> {cb['build']}
          <div class="ck-surfaces"><span>Surfaces:</span> {surfaces}</div></div>
        <div class="callout ck-learn"><strong>What you learn</strong><ul>{learn}</ul></div>
      </div>
      <h2 id="flow">Implementation flow</h2>
      <div class="diagram"><pre class="mermaid">{esc(cb['mermaid'])}</pre></div>
      <h2 id="steps">Step-by-step <span class="ck-uionly">UI only</span></h2>
      <p class="ck-steps-lead">Each step shows the exact navigation path, the fields to fill, the button to click,
        and a snapshot of the CALIBER screen you'll be on.</p>
      {render_steps(cb, folder, href_map)}
      {assets_section}
      <h2 id="gates">Evaluation &amp; quality gates</h2>
      {gates_tbl}
      <div class="callout ck-notes"><strong>Developer notes &amp; gotchas</strong><ul>{notes}</ul></div>
      {pager}"""


def render_index_body() -> str:
    cards = ""
    for track in TRACKS:
        track_cbs = [c for c in COOKBOOKS if c["track"] == track]
        if not track_cbs:
            continue
        cards += f'<h2 id="{slugify(track)}">{esc(track)}</h2><div class="ck-card-grid">'
        for cb in track_cbs:
            badges = badge(cb["level"], "ok") + badge(cb["time"], "orange")
            cards += f"""<a class="ck-card" href="{detail_filename(cb)}">
              <div class="ck-card-num">{esc(cb['num'])}</div>
              <strong>{esc(cb['title'])}</strong>
              <span class="ck-card-sub">{esc(cb['subtitle'])}</span>
              <div class="ck-badges">{badges}</div>
              <span class="ck-card-go">Open cookbook →</span>
            </a>"""
        cards += "</div>"
    return f"""
      <nav class="doc-breadcrumb" aria-label="Breadcrumb">
        <span>Cookbooks</span><span aria-hidden="true">/</span><span class="current">All recipes</span>
      </nav>
      <header class="doc-header">
        <p class="doc-eyebrow">Cookbooks</p>
        <h1>Cookbooks</h1>
        <p class="doc-lead">{INTRO['tagline']}</p>
        <div class="ck-meta">{"".join(badge(m) for m in INTRO['meta'])}</div>
      </header>
      {INTRO['body']}
      <h2 id="recipes">Pick a recipe</h2>
      <p class="ck-steps-lead">Each card opens a self-contained walkthrough — flow diagram, step-by-step UI
        snapshots, copy-paste assets, and quality gates.</p>
      {cards}"""


# ── shell ────────────────────────────────────────────────────────────────--
def topbar() -> str:
    return """<header class="topbar">
    <div class="topbar-row">
      <a class="topbar-brand" href="index.html" aria-label="{home_label}" title="{home_label}" style="text-decoration:none;color:inherit">
        <img src="caliber-icon.png" alt="{brand_short} logo"><strong>{brand_short}</strong>
      </a>
      <nav class="docs-section-tabs" id="docsSectionTabs" aria-label="Browse documentation sections"></nav>
      <div class="topbar-actions">
        <button type="button" class="topbar-search-trigger" id="topbarSearch" aria-label="Search docs" title="Search docs">
          <svg class="topbar-search-icon" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="11" cy="11" r="7"/><line x1="21" y1="21" x2="16.65" y2="16.65"/></svg>
          <span class="topbar-search-label">Search docs</span><span class="keycap" data-doc-search-key>⌘K</span>
        </button>
        <a class="topbar-cta" href="index.html#playbook-build">Quickstart</a>
        <button type="button" class="theme-toggle" id="themeToggle" aria-label="Toggle dark mode" title="Toggle light / dark theme">
          <svg class="icon-moon" width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"/></svg>
          <svg class="icon-sun" width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="5"/><line x1="12" y1="1" x2="12" y2="3"/><line x1="12" y1="21" x2="12" y2="23"/><line x1="4.22" y1="4.22" x2="5.64" y2="5.64"/><line x1="18.36" y1="18.36" x2="19.78" y2="19.78"/><line x1="1" y1="12" x2="3" y2="12"/><line x1="21" y1="12" x2="23" y2="12"/><line x1="4.22" y1="19.78" x2="5.64" y2="18.36"/><line x1="18.36" y1="5.64" x2="19.78" y2="4.22"/></svg>
        </button>
      </div>
    </div>
  </header>""".format(home_label=esc(DOCS_HOME_LABEL), brand_short=esc(BRAND_SHORT))


THEME_BOOT = """<script>
    (function () {
      try {
        var t = localStorage.getItem("caliber-docs-theme");
        if (t !== "light" && t !== "dark") t = window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light";
        document.documentElement.dataset.theme = t;
      } catch (e) { document.documentElement.dataset.theme = "light"; }
    })();
  </script>"""

COPY_JS = """<script>
    document.addEventListener("click", function (e) {
      var b = e.target.closest("[data-ck-copy]"); if (!b) return;
      var pre = b.closest(".ck-asset").querySelector("pre code");
      var txt = pre ? pre.textContent : "";
      (navigator.clipboard ? navigator.clipboard.writeText(txt) : Promise.reject()).then(function () {
        var old = b.textContent; b.textContent = "Copied"; b.classList.add("ok");
        setTimeout(function () { b.textContent = old; b.classList.remove("ok"); }, 1400);
      }).catch(function () { b.textContent = "Select + copy"; });
    });
  </script>"""


def page(title: str, body: str) -> str:
    return f"""<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{esc(title)} | {esc(BRAND_FULL)}</title>
  <meta name="description" content="CALIBER Cookbooks — UI-only, build-along recipes for the platform.">
  <link rel="icon" type="image/png" href="caliber-icon.png">
  {THEME_BOOT}
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="docs.css">
  <script src="https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.min.js"></script>
</head>

<body data-doc-page="module">
  <a class="skip-link" href="#docsContent">Skip to content</a>
  {topbar()}
  <button type="button" class="menu-toggle" id="menuToggle" aria-label="Toggle menu" aria-controls="docsSidebar" aria-expanded="false">
    <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="3" y1="6" x2="21" y2="6"/><line x1="3" y1="12" x2="21" y2="12"/><line x1="3" y1="18" x2="21" y2="18"/></svg>
  </button>
  <div class="layout">
    <aside class="sidebar" id="docsSidebar">
      <a class="sidebar-brand" href="index.html" aria-label="{esc(DOCS_HOME_LABEL)}" title="{esc(DOCS_HOME_LABEL)}" style="text-decoration:none;color:inherit">
        <img src="caliber-icon.png" alt="{esc(BRAND_SHORT)} logo"><div class="sidebar-brand-title">{esc(BRAND_SHORT)}</div>
      </a>
      <div class="sidebar-search"><input id="nav-filter" type="search" placeholder="Search docs and sections..." aria-label="Search docs and sections"></div>
      <nav id="docs-nav" aria-label="Documentation"></nav>
    </aside>
    <main class="main" id="docsContent">
      <article class="content doc-body ck-wide">
        {body}
        <footer><p>{esc(BRAND_FULL)} — Cookbooks — every recipe is UI-implementable on the shipped platform.
        Source + assets under <code>docs-site/cookbooks/&lt;nn&gt;-…/</code>. Regenerate with <code>python3 docs-site/cookbooks/training/build.py</code>.</p></footer>
      </article>
    </main>
    <aside class="toc" aria-label="On this page">
      <div class="toc-card"><div class="toc-title">On this page</div><nav class="toc-links" id="page-toc"></nav></div>
    </aside>
  </div>
  <script defer src="docs-nav.js"></script>
  <script defer src="docs.js"></script>
  {COPY_JS}
</body>

</html>
"""


def patch_docs_css() -> None:
    css = DOCS_CSS.read_text(encoding="utf-8")
    start = css.find(CSS_MARKER)
    if start != -1:
        css = css[:start].rstrip() + "\n"
    DOCS_CSS.write_text(css.rstrip() + "\n\n" + COOKBOOK_CSS, encoding="utf-8")


COOKBOOK_CSS = CSS_MARKER + """
.ck-meta{display:flex;flex-wrap:wrap;gap:.4rem;margin-top:.7rem}
.ck-badge{display:inline-block;border:1px solid var(--border);background:var(--bg-card);color:var(--text-muted);border-radius:999px;padding:.1rem .6rem;font-size:.72rem;font-weight:600;font-family:var(--mono)}
.ck-badge.ck-track{border-color:var(--accent);color:var(--accent);background:var(--accent-glow)}
.ck-badge.ck-ok{border-color:var(--green);color:var(--green);background:var(--green-bg)}
.ck-badge.ck-orange{border-color:var(--orange);color:var(--orange);background:var(--orange-bg)}
.ck-badge.ck-surface{font-family:var(--font)}
.ck-badges{display:flex;flex-wrap:wrap;gap:.35rem;margin:.5rem 0}
.ck-cols{display:grid;grid-template-columns:1.1fr 1fr;gap:1rem;margin:1rem 0}
@media(max-width:820px){.ck-cols{grid-template-columns:1fr}}
.ck-cols .callout{margin:0}
.ck-learn ul{margin:.4rem 0 0;padding-left:1.1rem}.ck-learn li{margin:.2rem 0}
.ck-surfaces{margin-top:.6rem;font-size:.85rem}.ck-surfaces span{color:var(--text-dim);margin-right:.3rem}
.ck-uionly{font-size:.6em;font-weight:700;letter-spacing:.04em;vertical-align:middle;background:var(--green);color:#fff;border-radius:999px;padding:.12rem .55rem;margin-left:.4rem}
.ck-steps-lead,.ck-assets-lead{color:var(--text-muted);font-size:.92rem;margin:.2rem 0 1rem}
/* index cards */
.ck-card-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(17rem,1fr));gap:1rem;margin:1rem 0 2rem}
.ck-card{display:flex;flex-direction:column;gap:.35rem;border:1px solid var(--border);border-radius:var(--radius-sm);background:var(--bg-card);padding:1.1rem 1.15rem;transition:border-color .15s,transform .15s,box-shadow .15s}
.ck-card:hover{border-color:var(--accent);transform:translateY(-2px);box-shadow:var(--shadow)}
.ck-card-num{width:1.8rem;height:1.8rem;border-radius:.55rem;background:var(--accent);color:#fff;font-weight:700;font-size:.9rem;display:flex;align-items:center;justify-content:center}
.ck-card strong{font-size:1.06rem;color:var(--text);margin-top:.2rem}
.ck-card-sub{color:var(--text-muted);font-size:.86rem;line-height:1.5;flex:1}
.ck-card-go{color:var(--accent);font-weight:600;font-size:.85rem;margin-top:.3rem}
/* steps */
.ck-steps{list-style:none;counter-reset:ck;padding:0;margin:.4rem 0}
.ck-steps>li{counter-increment:ck;position:relative;padding:1rem 1rem 1rem 3rem;border:1px solid var(--border);border-radius:var(--radius-sm);margin:.7rem 0;background:var(--bg-card)}
.ck-steps>li::before{content:counter(ck);position:absolute;left:.85rem;top:1rem;width:1.55rem;height:1.55rem;border-radius:50%;background:var(--accent-glow);color:var(--accent);font-weight:700;font-size:.82rem;display:flex;align-items:center;justify-content:center}
.ck-step-grid{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,21rem);gap:1.5rem;align-items:start}
@media(max-width:1000px){.ck-step-grid{grid-template-columns:1fr}}
.ck-step-head{display:flex;flex-wrap:wrap;gap:.4rem;align-items:center;margin-bottom:.4rem}
.ck-where{background:var(--text);color:var(--bg);padding:.12rem .55rem;border-radius:.4rem;font-size:.76rem;font-weight:600}
[data-theme=dark] .ck-where{background:#0d1320;color:#e2e8f0;border:1px solid var(--border)}
.ck-made{background:var(--green-bg);color:var(--green);border:1px solid var(--green);border-radius:.4rem;padding:.05rem .45rem;font-size:.7rem;font-weight:600;font-family:var(--mono)}
.ck-assetref{font-family:var(--mono);font-size:.72rem;color:var(--accent);border:1px solid var(--accent);border-radius:.4rem;padding:.05rem .45rem;background:var(--accent-glow)}
.ck-step-do{color:var(--text)}.ck-step-do code{font-size:.85em}
.ck-fill{margin:.6rem 0 .2rem;border:1px solid var(--border-light);border-radius:.5rem;overflow:hidden}
.ck-fill-t{background:var(--bg-card-hover);font-size:.68rem;text-transform:uppercase;letter-spacing:.06em;color:var(--text-dim);font-weight:700;padding:.3rem .6rem}
.ck-fill table{width:100%;border-collapse:collapse;font-size:.84rem}
.ck-fill td{padding:.35rem .6rem;border-top:1px solid var(--border-light);vertical-align:top}
.ck-fill td:first-child{font-weight:600;color:var(--accent);white-space:nowrap;width:1%;font-family:var(--mono);font-size:.82em}
.ck-click{margin:.55rem 0 .2rem;font-size:.86rem;color:var(--text-muted)}
.ck-btn{display:inline-block;background:var(--accent);color:#fff;font-weight:600;font-size:.78rem;padding:.16rem .65rem;border-radius:.5rem;margin:0 .1rem}
.ck-see{margin-top:.5rem;font-size:.84rem;color:var(--text-muted);background:var(--accent-glow);border-left:3px solid var(--accent);border-radius:.3rem;padding:.4rem .65rem}
.ck-notes ul{margin:.4rem 0 0;padding-left:1.1rem}.ck-notes li{margin:.25rem 0}
/* wider canvas for cookbook pages so steps + snapshots breathe */
.doc-body.ck-wide{max-width:60rem}
/* per-step snapshot — a compact, focused shot of the relevant screen */
.ck-step-snap{align-self:start}
.ck-snap-label{font-size:.62rem;text-transform:uppercase;letter-spacing:.09em;color:var(--text-dim);font-weight:700;margin-bottom:.45rem}
.ck-mock{margin:0;border:1px solid var(--border);border-radius:var(--radius-sm);overflow:hidden;box-shadow:var(--shadow);background:var(--bg-card)}
.ck-mk-chrome{background:#1f2937;padding:.4rem .6rem;display:flex;align-items:center;gap:.32rem}
.ck-mk-dot{width:.52rem;height:.52rem;border-radius:50%;background:#475569}
.ck-mk-url{margin-left:.45rem;background:#0b0f1a;color:#94a3b8;font-size:.65rem;padding:.16rem .6rem;border-radius:.35rem;font-family:var(--mono);overflow:hidden;text-overflow:ellipsis;white-space:nowrap;flex:1}
.ck-mk-screen{padding:.9rem .95rem;background:var(--bg)}
.ck-mk-bar{display:flex;align-items:center;gap:.5rem;margin-bottom:.75rem}
.ck-mk-page{background:var(--accent-glow);color:var(--accent);border:1px solid var(--accent);border-radius:.4rem;padding:.12rem .55rem;font-size:.65rem;font-weight:700;font-family:var(--mono);white-space:nowrap}
.ck-mk-title{font-weight:700;font-size:.9rem;color:var(--text);overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.ck-mk-panel{background:var(--bg-card);border:1px solid var(--border-light);border-radius:.55rem;padding:.85rem}
.ck-mk-field{display:block;margin-bottom:.6rem}
.ck-mk-field:last-child{margin-bottom:0}
.ck-mk-label{display:block;font-size:.6rem;text-transform:uppercase;letter-spacing:.05em;color:var(--text-dim);font-weight:700;margin-bottom:.2rem}
.ck-mk-input{display:block;background:var(--bg);border:1px solid var(--border);border-radius:.4rem;padding:.38rem .55rem;color:var(--text-muted);font-size:.76rem;min-height:1.85rem;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.ck-mk-actions{margin-top:.8rem;display:flex;gap:.45rem;flex-wrap:wrap}
.ck-mk-btn{background:var(--accent);color:#fff;font-weight:600;font-size:.76rem;padding:.36rem .9rem;border-radius:.45rem;box-shadow:0 1px 2px rgba(124,58,237,.25)}
.ck-mk-btn.ghost{background:transparent;color:var(--accent);border:1px solid var(--accent);box-shadow:none}
.ck-mk-empty{color:var(--text-dim);font-size:.78rem;font-style:italic}
/* inlined assets */
.ck-asset{margin:.8rem 0;border:1px solid var(--border);border-radius:var(--radius-sm);overflow:hidden;scroll-margin-top:calc(var(--topbar-h) + 1rem)}
.ck-asset-bar{display:flex;align-items:center;justify-content:space-between;background:var(--bg-card-hover);padding:.4rem .7rem;border-bottom:1px solid var(--border)}
.ck-asset-name{font-family:var(--mono);font-size:.78rem;color:var(--accent);font-weight:600}
.ck-copy{font-size:.72rem;font-weight:600;color:var(--text-muted);background:var(--bg-card);border:1px solid var(--border);border-radius:.4rem;padding:.18rem .6rem;cursor:pointer}
.ck-copy:hover{border-color:var(--accent);color:var(--accent)}
.ck-copy.ok{color:var(--green);border-color:var(--green)}
.ck-asset pre{margin:0;border:0;border-radius:0;max-height:24rem;overflow:auto}
.ck-asset-trunc{font-size:.76rem;color:var(--text-dim);padding:.4rem .7rem;border-top:1px solid var(--border)}
/* pager */
.ck-pager{display:flex;justify-content:space-between;align-items:center;gap:1rem;margin:2.2rem 0 1rem;padding-top:1.2rem;border-top:1px solid var(--border)}
.ck-pager a{font-weight:600;font-size:.9rem}
.ck-pager-up{color:var(--text-muted)}
"""


def main() -> None:
    # 1. detail pages
    n = len(COOKBOOKS)
    for i, cb in enumerate(COOKBOOKS):
        prev_cb = COOKBOOKS[i - 1] if i > 0 else None
        next_cb = COOKBOOKS[i + 1] if i < n - 1 else None
        body = render_detail_body(cb, prev_cb, next_cb)
        (DOCS_SITE / detail_filename(cb)).write_text(
            page(f"Cookbook {cb['num']}: {cb['title']}", body), encoding="utf-8"
        )
    # 2. index
    INDEX_OUT.write_text(page("Cookbooks", render_index_body()), encoding="utf-8")
    # 3. nav manifest for build-docs.mjs (Overview + one link per cookbook)
    nav = [{"href": "m-16-cookbooks.html", "label": "All cookbooks"}]
    nav += [{"href": detail_filename(cb), "label": f"{cb['num']} · {cb['title']}"} for cb in COOKBOOKS]
    NAV_JSON.write_text(json.dumps(nav, indent=2) + "\n", encoding="utf-8")
    # 4. styles
    patch_docs_css()
    overrides = sum(1 for cb in COOKBOOKS if (f := folder_for(cb["num"])) and (f / "training-steps.json").exists())
    print(f"wrote index + {n} detail pages + cookbooks-nav.json ({overrides} detailed-step overrides) + patched docs.css")


if __name__ == "__main__":
    main()
