"""Contracts for the flattened, machine-readable documentation output.

``llms.txt`` advertises the generated ``m-*.md`` files for programmatic use.
Those files live in one flat directory even though their Markdown sources are
nested under ``docs/``. A source-relative cross-reference can therefore exist
and render correctly in the source tree while being broken in the published
copy. These checks pin the published contract independently of the generator.
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
from functools import cache
from pathlib import Path
from urllib.parse import unquote, urlsplit

REPO_ROOT = Path(__file__).resolve().parents[2]
DOCS_SITE = REPO_ROOT / "docs-site"
DOCS_SOURCE = REPO_ROOT / "docs"
LAYERED_ARCHITECTURE = REPO_ROOT / "ARCHITECTURE.md"
PUBLIC_DOCS = REPO_ROOT / "caliber" / "caliber-ui" / "public" / "docs"
PACKAGED_DOCS = REPO_ROOT / "caliber" / "src" / "caliber" / "ui" / "docs"
MARKDOWN_LINK = re.compile(r"!?\[[^\]\n]*\]\(([^\n)]*)\)")
MODULE_ENTRY = re.compile(r'\{\s*md: "([^"]+)",\s*out: "([^"]+\.html)"')
ALLOWED_AUDIENCES = {
    "developer",
    "system-user",
    "operator",
    "architect",
    "evaluator",
    "decision-maker",
}
ALLOWED_DOC_TYPES = {
    "tutorial",
    "how-to",
    "concept",
    "reference",
    "runbook",
    "example",
    "strategy",
}
ALLOWED_STABILITY = {"ga", "beta", "experimental", "internal"}
REQUIRED_SOURCE_FRONT_MATTER_KEYS = frozenset(
    {
        "audience",
        "doc_type",
        "product_area",
        "stability",
        "prerequisites",
        "reviewed_on",
        "version_applicability",
        "tags",
    }
)
HAND_AUTHORED_PAGES = {
    "index.html",
    "interactive-layered-architecture.html",
    "walkthrough.html",
    "presentation.html",
    "presentation_timed.html",
}

#: Provenance banner the generator stamps onto every published page. Spelled out
#: here rather than scraped from the generator so a change to the wording has to
#: be made deliberately in both places -- the point of the banner is that it
#: names the real source, and a test that read it from the generator could not
#: catch the generator naming the wrong one.
GENERATED_BANNER = (
    "<!-- Generated by docs-site/build-docs.mjs from {source}. "
    "Do not edit this file: edit the source and re-run the build "
    "(caliber/caliber-ui: npm run sync:docs). -->"
)


def _expected_banner(source: Path) -> str:
    return GENERATED_BANNER.format(source=source.resolve().relative_to(REPO_ROOT).as_posix())


def _destination(raw: str) -> str:
    """Return a Markdown link destination without an optional title."""
    value = raw.strip()
    if value.startswith("<"):
        close = value.find(">")
        return value[1:close] if close >= 0 else value
    return value.split(maxsplit=1)[0] if value else ""


def _local_markdown_links(path: Path) -> list[str]:
    links: list[str] = []
    for match in MARKDOWN_LINK.finditer(path.read_text(encoding="utf-8")):
        destination = _destination(match.group(1))
        parsed = urlsplit(destination)
        if (
            not destination
            or parsed.scheme
            or parsed.netloc
            or destination.startswith(("#", "mailto:", "data:"))
        ):
            continue
        links.append(destination)
    return links


def _manifest_modules() -> list[tuple[str, str]]:
    """Read the public module mapping without executing the mutating JS build."""
    builder = (DOCS_SITE / "build-docs.mjs").read_text(encoding="utf-8")
    return MODULE_ENTRY.findall(builder)


def _without_link_destinations(markdown: str) -> str:
    """Keep authored text/labels while ignoring the expected flattened href rewrite."""

    def replace_destination(match: re.Match[str]) -> str:
        whole = match.group(0)
        start = match.start(1) - match.start(0)
        end = match.end(1) - match.start(0)
        return f"{whole[:start]}<LINK>{whole[end:]}"

    return MARKDOWN_LINK.sub(replace_destination, markdown)


def _normalize_published_markdown(markdown: str, source: Path) -> str:
    """Mirror the generator's removal of repository-only presentation chrome."""
    if source.resolve() != LAYERED_ARCHITECTURE:
        return markdown
    wrappers = {
        '<div align="center">',
        "</div>",
        '<div align="center"><sub>',
        "</sub></div>",
    }
    lines = []
    for line in markdown.replace("\r\n", "\n").split("\n"):
        stripped = line.strip()
        if stripped in wrappers:
            continue
        if re.fullmatch(
            r'<img\s+src="docs-site/caliber\.png"[^>]*?/?>',
            stripped,
            flags=re.IGNORECASE,
        ):
            continue
        lines.append(line)
    return "\n".join(lines).replace("&nbsp;", " ")


@cache
def _generated_sdk_fragment(kind: str) -> str:
    generator = DOCS_SITE / "generate_sdk_docs.py"
    return subprocess.run(
        [sys.executable, "-B", str(generator), kind],
        check=True,
        capture_output=True,
        text=True,
    ).stdout.strip()


@cache
def _generated_rest_api_fragment() -> str:
    generator = DOCS_SITE / "generate_rest_api_docs.py"
    return subprocess.run(
        [sys.executable, "-B", str(generator)],
        check=True,
        capture_output=True,
        text=True,
    ).stdout.strip()


def _materialize_source_markdown(markdown: str) -> str:
    return (
        markdown.replace("{{SDK_API_REFERENCE}}", _generated_sdk_fragment("reference"))
        .replace("{{SDK_COOKBOOKS}}", _generated_sdk_fragment("cookbooks"))
        .replace("{{REST_API_ROUTE_INVENTORY}}", _generated_rest_api_fragment())
    )


def _strip_front_matter(markdown: str) -> str:
    if not markdown.startswith("---\n"):
        return markdown
    _, _, remainder = markdown.partition("\n---\n")
    return remainder if remainder else markdown


def _front_matter_keys(markdown: str) -> set[str]:
    if not markdown.startswith("---\n"):
        return set()

    keys: set[str] = set()
    for line in markdown.splitlines()[1:]:
        if line == "---":
            break
        if not line or line.startswith("  - ") or line[:1].isspace():
            continue
        key, sep, _ = line.partition(":")
        if sep:
            keys.add(key.strip())
    return keys


#: Site files that are not per-module output. Hoisted out of ``_served_site_files``
#: so the coverage assertions below can name what they expect rather than counting.
FIXED_SITE_FILES = frozenset(
    {
        "index.html",
        "docs.css",
        "docs.js",
        "docs-nav.js",
        "search-index.json",
        "llms.txt",
        "interactive-layered-architecture.html",
        "presentation.html",
        "presentation_timed.html",
        "walkthrough.html",
    }
)


def _served_site_files(directory: Path) -> set[str]:
    return {
        path.name
        for path in directory.iterdir()
        if path.is_file()
        and (
            path.name in FIXED_SITE_FILES
            or (path.name.startswith("m-") and path.suffix in {".html", ".md"})
        )
    }


def _served_copy(source: Path) -> str:
    content = source.read_text(encoding="utf-8")
    if source.suffix == ".html":
        content = content.replace('"caliber-icon.png"', '"../caliber-icon.png"')
        content = content.replace('"caliber.png"', '"../caliber.png"')
    return content


def test_all_manifest_markdown_is_current_and_published() -> None:
    """Pin every manifest module to its flattened generated Markdown copy.

    Link destinations intentionally change during flattening. Removing only those
    destinations lets this independent test catch stale prose (the failure mode
    that previously left the refinement-loop and roadmap copies behind) while the
    link-resolution test below validates the rewritten destinations themselves.
    """
    modules = _manifest_modules()
    assert modules, "the manifest parsed empty; every assertion below would pass vacuously"
    assert modules[0] == (
        "../ARCHITECTURE.md",
        "m-00-layered-architecture.html",
    )

    for source_name, html_name in modules:
        source = DOCS_SOURCE / source_name
        generated = DOCS_SITE / html_name.replace(".html", ".md")
        assert source.is_file(), source_name
        assert generated.is_file(), generated.name

        published = generated.read_text(encoding="utf-8")
        banner = _expected_banner(source)
        assert published.startswith(f"{banner}\n\n"), (
            f"{generated.name} must open with the generated-file banner naming "
            f"{source_name}; a hand-edit here is reverted by the next build"
        )
        body = published[len(banner) + 2 :]

        assert _without_link_destinations(body) == (
            _without_link_destinations(
                _normalize_published_markdown(
                    _strip_front_matter(
                        _materialize_source_markdown(source.read_text(encoding="utf-8"))
                    ),
                    source,
                )
            )
        ), f"stale generated Markdown for {source_name}"


def test_generated_markdown_sources_define_front_matter_metadata() -> None:
    modules = _manifest_modules()
    assert modules, "the manifest parsed empty; the source metadata contract cannot be checked"

    for source_name, _ in modules:
        if source_name == "../ARCHITECTURE.md":
            continue

        source = DOCS_SOURCE / source_name
        markdown = source.read_text(encoding="utf-8")
        assert markdown.startswith("---\n"), (
            f"{source_name} is published through docs-site/build-docs.mjs and must define "
            "source-owned front matter"
        )

        keys = _front_matter_keys(markdown)
        missing = REQUIRED_SOURCE_FRONT_MATTER_KEYS - keys
        assert not missing, f"{source_name} missing front matter keys: {sorted(missing)}"


def test_every_generated_html_page_names_its_source() -> None:
    """The HTML half carries the same provenance banner as the Markdown half.

    ``m-*.html`` is build output too, and an author editing it gets no signal
    from the filename. Pin the banner on both halves so neither can drift into
    looking hand-maintained.
    """
    modules = _manifest_modules()
    assert modules, "the manifest parsed empty; the loop below would pass vacuously"

    for source_name, html_name in modules:
        source = DOCS_SOURCE / source_name
        page = DOCS_SITE / html_name
        assert page.is_file(), html_name
        expected = f"<!DOCTYPE html>\n{_expected_banner(source)}\n"
        assert page.read_text(encoding="utf-8").startswith(expected), (
            f"{html_name} must open with the generated-file banner naming {source_name}"
        )


def test_layered_architecture_render_and_links_are_published() -> None:
    """The repository-level map renders cleanly in HTML and flat Markdown."""
    assert LAYERED_ARCHITECTURE.is_file()
    html = (DOCS_SITE / "m-00-layered-architecture.html").read_text(encoding="utf-8")
    markdown = (DOCS_SITE / "m-00-layered-architecture.md").read_text(encoding="utf-8")

    assert '<h1 id="top">CALIBER — Layered Architecture</h1>' in html
    assert '<pre class="mermaid">' in html
    assert "<hr>" in html
    assert "&lt;div align=" not in html
    assert 'href="m-01-platform.html"' in html
    assert 'href="m-17-competitive-analysis.html"' in html

    # The provenance banner is the only thing allowed above the H1; the
    # repository-only presentation chrome around it must be stripped.
    banner = _expected_banner(LAYERED_ARCHITECTURE)
    assert markdown.startswith(f"{banner}\n\n")
    assert markdown[len(banner) + 2 :].lstrip().startswith("# CALIBER — Layered Architecture")
    assert '<div align="center">' not in markdown
    assert "docs-site/caliber.png" not in markdown
    assert "(m-01-platform.md)" in markdown
    assert "(m-17-competitive-analysis.md)" in markdown
    assert "(walkthrough.html)" in markdown
    assert (
        "https://github.com/rrahimi-uci/caliber-suite/blob/main/caliber/src/caliber/server.py"
    ) in markdown
    assert (
        "https://github.com/rrahimi-uci/caliber-suite/tree/main/caliber/src/caliber/routes"
    ) in markdown


def test_llms_index_and_flattened_markdown_links_resolve_locally() -> None:
    llms = DOCS_SITE / "llms.txt"
    indexed = {
        unquote(urlsplit(link).path)
        for link in _local_markdown_links(llms)
        if urlsplit(link).path.endswith(".md")
    }
    generated = {path.name for path in DOCS_SITE.glob("m-*.md")}

    assert indexed == generated, (
        "llms.txt must index every generated Markdown module exactly once; "
        f"missing={sorted(generated - indexed)}, stale={sorted(indexed - generated)}"
    )

    broken: list[str] = []
    escaped: list[str] = []
    docs_root = DOCS_SITE.resolve()
    for name in sorted(generated):
        source = DOCS_SITE / name
        for link in _local_markdown_links(source):
            parsed = urlsplit(link)
            target = (source.parent / unquote(parsed.path)).resolve()
            try:
                target.relative_to(docs_root)
            except ValueError:
                escaped.append(f"{name}: {link}")
                continue
            if not target.is_file():
                broken.append(f"{name}: {link}")

    assert not escaped, "flattened Markdown links escape docs-site:\n" + "\n".join(escaped)
    assert not broken, "flattened Markdown links have missing targets:\n" + "\n".join(broken)


def test_the_manifest_and_the_published_site_are_in_bijection() -> None:
    """Every manifest entry is published, and every published module is in the manifest.

    This replaced two count assertions --- ``len(modules) == 21`` and
    ``len(expected) == 67``. A count detects that something moved without saying
    what: adding ``docs/runbook.md`` to the manifest produced ``assert 21 == 20``,
    which names neither the file nor which side changed, and both numbers then had
    to be bumped by hand. It is also satisfiable for the wrong reason, since one
    addition and one removal cancel.

    A bijection carries the information the count was standing in for. Adding a
    module to the manifest without publishing it, publishing one that is not in the
    manifest, or dropping either, each fails with the file named. Nothing needs
    bumping when the set legitimately grows.
    """
    declared = {out for _, out in _manifest_modules()}
    published = {
        path.name
        for path in DOCS_SITE.iterdir()
        if path.is_file() and path.name.startswith("m-") and path.suffix == ".html"
    }
    # Cookbook pages come from ``docs-site/cookbooks/<slug>/`` rather than from
    # the module manifest, so they are checked against their own sources. The
    # index over them is generated too, and is named rather than counted.
    cookbooks = {name for name in published if name.startswith("m-cookbook-")}
    cookbook_index = {"m-16-cookbooks.html"}

    assert declared, "the manifest parsed empty"
    assert declared <= published, (
        f"declared in the manifest but not published: {sorted(declared - published)}"
    )
    unexplained = published - declared - cookbooks - cookbook_index
    assert not unexplained, (
        "published modules that no manifest entry and no cookbook source accounts "
        f"for: {sorted(unexplained)}"
    )

    cookbook_sources = {
        path.name
        for path in (DOCS_SITE / "cookbooks").iterdir()
        if path.is_dir() and path.name[:2].isdigit()
    }
    assert len(cookbooks) == len(cookbook_sources), (
        f"{len(cookbook_sources)} cookbook sources produced {len(cookbooks)} pages; "
        f"sources: {sorted(cookbook_sources)}\n  pages: {sorted(cookbooks)}"
    )

    missing_markdown = {
        name.replace(".html", ".md")
        for name in declared
        if not (DOCS_SITE / name.replace(".html", ".md")).is_file()
    }
    assert not missing_markdown, (
        f"declared modules with no flat Markdown: {sorted(missing_markdown)}"
    )


def test_all_materialized_docs_copies_match_docs_site() -> None:
    """The tracked public tree and any built package tree match the served site."""
    expected = _served_site_files(DOCS_SITE)

    # Coverage, not a count. Without this the equality below is satisfied by two
    # empty directories, which is the failure mode a bare ``len(...) == 67`` was
    # really guarding against -- while also having to be re-typed whenever a
    # module was added.
    declared = {out for _, out in _manifest_modules()}
    assert expected >= FIXED_SITE_FILES, (
        f"site is missing fixed files: {sorted(FIXED_SITE_FILES - expected)}"
    )
    assert declared <= expected, f"site is missing declared modules: {sorted(declared - expected)}"

    assert _served_site_files(PUBLIC_DOCS) == expected

    for name in sorted(expected):
        expected_content = _served_copy(DOCS_SITE / name)
        assert (PUBLIC_DOCS / name).read_text(encoding="utf-8") == expected_content, name

    # ``src/caliber/ui`` is a build output excluded from Git. Check it whenever
    # the UI prebuild/package step has materialized it, without making a clean
    # backend-only checkout depend on an earlier Node build.
    if PACKAGED_DOCS.is_dir():
        assert _served_site_files(PACKAGED_DOCS) == expected
        for name in sorted(expected):
            expected_content = _served_copy(DOCS_SITE / name)
            assert (PACKAGED_DOCS / name).read_text(encoding="utf-8") == expected_content, name


def test_no_published_page_links_to_an_anchor_it_does_not_contain() -> None:
    """A dead in-page link is worse than plain text: it invites a click.

    Cross-references are generated, so a dangling one is a silent product of the
    generator rather than a typo somebody can spot in review. Three shipped: two
    ``Raises`` entries linking exception names the reference does not document
    (``ValueError`` is a builtin; ``error_for_response`` is a factory, not a
    type), and ``Capabilities.extensibility`` pointing at a class that was
    missing from its own module's ``__all__`` and so never rendered.
    """
    dangling: dict[str, list[str]] = {}
    for page in sorted(DOCS_SITE.glob("m-*.html")):
        html = page.read_text(encoding="utf-8")
        ids = set(re.findall(r'id="([^"]+)"', html))
        targets = set(re.findall(r'href="#([^"]+)"', html))
        missing = sorted(target for target in targets - ids if target)
        if missing:
            dangling[page.name] = missing

    assert not dangling, f"pages link to anchors they do not define: {dangling}"


def _docs_data() -> dict[str, object]:
    text = (DOCS_SITE / "docs-nav.js").read_text(encoding="utf-8")
    match = re.search(r"window\.DOCS_DATA = (\{[\s\S]*?\});\nwindow\.DOCS_NAV =", text)
    assert match, "docs-nav.js no longer exposes window.DOCS_DATA"
    return json.loads(match.group(1))


def _search_results(query: str, limit: int = 12) -> list[dict[str, object]]:
    payload = json.loads((DOCS_SITE / "search-index.json").read_text(encoding="utf-8"))
    pages = payload["pages"]
    q = query.strip().lower()
    terms = [term.strip() for term in q.split() if term.strip()]
    scored: list[tuple[int, dict[str, object]]] = []
    for entry in pages:
        title = str(entry.get("label", "")).lower()
        page_label = str(entry.get("page_label", "")).lower()
        href = str(entry.get("href", "")).lower()
        section = str(entry.get("section", "")).lower()
        summary = str(entry.get("summary", "")).lower()
        symbol_list = [str(item) for item in entry.get("symbols", [])]
        route_list = [str(item) for item in entry.get("routes", [])]
        heading_list = [str(item) for item in entry.get("headings", [])]
        symbols = " ".join(symbol_list).lower()
        routes = " ".join(route_list).lower()
        headings = " ".join(heading_list).lower()
        body = str(entry.get("body", "")).lower()
        tags = " ".join(entry.get("tags", [])).lower()
        doc_type = str(entry.get("doc_type", "")).lower()
        audience = " ".join(entry.get("audience", [])).lower()
        is_reference_page = doc_type == "reference" or section == "reference"
        full = " ".join(
            [title, page_label, href, section, summary, symbols, routes, headings, body, tags, doc_type, audience]
        )
        exact_symbol_match = any(item.lower() == q for item in symbol_list)
        exact_route_match = any(item.lower() == q for item in route_list)
        exact_heading_match = any(item.lower() == q for item in heading_list)
        score = 0
        if title == q:
            score += 140
        if page_label == q:
            score += 95
        if exact_symbol_match:
            score += 220
        if exact_route_match:
            score += 210
        if exact_heading_match:
            score += 120
        if q in symbols:
            score += 135
        if q in routes:
            score += 125
        if is_reference_page and q in symbols:
            score += 80
        if is_reference_page and q in routes:
            score += 80
        if q in href:
            score += 110
        if q in title:
            score += 100
        if q in page_label:
            score += 65
        if q in symbols:
            score += 50
        if q in routes:
            score += 45
        if q in headings:
            score += 70
        if q in summary:
            score += 55
        if q in section:
            score += 35
        if q in doc_type:
            score += 20

        ok = True
        for term in terms:
            if term in title:
                score += 18
            if term in page_label:
                score += 10
            if term in symbols:
                score += 26
            if term in routes:
                score += 24
            if term in headings:
                score += 12
            if term in summary:
                score += 8
            if term in tags:
                score += 6
            if term in body:
                score += 3
            if term not in full:
                ok = False
                break
        if ok and score > 0:
            scored.append((score, entry))

    scored.sort(
        key=lambda item: (
            -item[0],
            0 if item[1].get("result_type", "page") == "page" else 1,
            str(item[1].get("label", "")),
        )
    )
    return [entry for _, entry in scored[:limit]]


def test_nav_reflects_the_refactored_information_architecture() -> None:
    data = _docs_data()
    sections = data["sections"]
    assert [section["section"] for section in sections] == [
        "Start here",
        "Use CALIBER",
        "Build & integrate",
        "Operate CALIBER",
        "Examples",
        "Reference",
        "Architecture",
        "Strategy",
    ]

    links_by_section = {
        section["section"]: {link["href"] for link in section.get("links", [])}
        for section in sections
    }
    assert "walkthrough.html" in links_by_section["Operate CALIBER"]
    assert "m-32-local-bring-up.html" in links_by_section["Operate CALIBER"]
    assert "m-37-five-minute-quickstart.html" in links_by_section["Start here"]
    assert "m-30-choose-your-path.html" in links_by_section["Start here"]
    assert "m-35-decision-maker-overview.html" in links_by_section["Start here"]
    assert "m-20-sdk-guide.html" in links_by_section["Build & integrate"]
    assert "m-31-auth-and-project-scoping.html" in links_by_section["Build & integrate"]
    assert "m-36-sdk-vs-rest-api.html" in links_by_section["Build & integrate"]
    assert "m-53-error-handling-and-retries.html" in links_by_section["Build & integrate"]
    assert "m-54-ci-cd-automation.html" in links_by_section["Build & integrate"]
    assert "m-55-developer-troubleshooting.html" in links_by_section["Build & integrate"]
    assert "m-38-use-prompts.html" in links_by_section["Use CALIBER"]
    assert "m-42-use-workflows.html" in links_by_section["Use CALIBER"]
    assert "m-47-use-review-and-release-flows.html" in links_by_section["Use CALIBER"]
    assert "m-48-configuration-and-provider-setup.html" in links_by_section["Operate CALIBER"]
    assert "m-50-health-and-readiness.html" in links_by_section["Operate CALIBER"]
    assert "m-21-sdk-reference.html" in links_by_section["Reference"]
    assert "m-56-config-and-environment-reference.html" in links_by_section["Reference"]
    assert "m-34-architecture-reader-guide.html" in links_by_section["Architecture"]
    assert "m-02-prompts.html" in links_by_section["Architecture"]
    assert "m-33-trust-and-governance.html" in links_by_section["Use CALIBER"]
    assert "m-02-prompts.html" not in links_by_section["Use CALIBER"]
    assert "presentation.html" not in {
        href for hrefs in links_by_section.values() for href in hrefs
    }
    assert "presentation_timed.html" not in {
        href for hrefs in links_by_section.values() for href in hrefs
    }


def test_landing_page_stays_orientation_first_and_keeps_collateral_secondary() -> None:
    html = (DOCS_SITE / "index.html").read_text(encoding="utf-8")

    assert "<h2>Choose your path</h2>" in html
    assert "<h2>Browse by documentation area</h2>" in html
    assert "<h2>First success</h2>" in html
    assert "<h2>Featured references</h2>" in html
    assert "<h2>Secondary resources</h2>" in html
    assert 'href="walkthrough.html"' in html
    assert 'href="interactive-layered-architecture.html"' in html
    assert 'href="presentation.html"' in html
    assert 'href="presentation_timed.html"' in html

    for unexpected in [
        "Aria: the agentic copilot",
        "Verification and calibration",
        "Workflow runtime and QA",
        "<h2>Configuration</h2>",
        "<h2>Observability and operations</h2>",
        "<h2>Security</h2>",
        "<h2>FAQ</h2>",
        'class="guide-section"',
    ]:
        assert unexpected not in html


def test_page_metadata_is_complete_and_uses_allowed_values() -> None:
    data = _docs_data()
    pages = data["pages"]
    assert pages, "docs-nav.js published no page metadata"

    for page in pages:
        assert page["href"], page
        assert page["label"], page
        assert page["section"], page
        assert page["section_id"], page
        assert page["doc_type"] in ALLOWED_DOC_TYPES, page
        assert isinstance(page["prerequisites"], list), page
        assert page["stability"] in ALLOWED_STABILITY, page
        assert page["reviewed_on"], page
        assert page["version_applicability"], page
        assert page["audience"], page
        assert set(page["audience"]).issubset(ALLOWED_AUDIENCES), page


def test_hand_authored_pages_have_metadata_and_search_records() -> None:
    data = _docs_data()
    nav_pages = {page["href"]: page for page in data["pages"]}
    search_pages = {
        page["href"]: page
        for page in json.loads((DOCS_SITE / "search-index.json").read_text(encoding="utf-8"))["pages"]
    }

    for href in HAND_AUTHORED_PAGES:
        assert href in nav_pages, f"{href} missing from docs-nav metadata"
        assert href in search_pages, f"{href} missing from search-index"
        assert nav_pages[href]["doc_type"] in ALLOWED_DOC_TYPES
        assert nav_pages[href]["stability"] in ALLOWED_STABILITY
        assert nav_pages[href]["audience"], href
        assert search_pages[href]["section"], href

    assert nav_pages["walkthrough.html"]["prerequisites"], nav_pages["walkthrough.html"]
    assert nav_pages["interactive-layered-architecture.html"]["prerequisites"], (
        nav_pages["interactive-layered-architecture.html"]
    )


def test_search_index_covers_generated_and_hand_authored_pages() -> None:
    payload = json.loads((DOCS_SITE / "search-index.json").read_text(encoding="utf-8"))
    pages = payload["pages"]
    assert pages, "search-index.json published no pages"

    by_href = {page["href"]: page for page in pages}
    for href in [
        "index.html",
        "m-37-five-minute-quickstart.html",
        "m-30-choose-your-path.html",
        "m-35-decision-maker-overview.html",
        "walkthrough.html",
        "m-32-local-bring-up.html",
        "m-38-use-prompts.html",
        "m-42-use-workflows.html",
        "m-48-configuration-and-provider-setup.html",
        "m-50-health-and-readiness.html",
        "interactive-layered-architecture.html",
        "m-20-sdk-guide.html",
        "m-31-auth-and-project-scoping.html",
        "m-36-sdk-vs-rest-api.html",
        "m-53-error-handling-and-retries.html",
        "m-55-developer-troubleshooting.html",
        "m-29-rest-api-reference.html",
        "m-56-config-and-environment-reference.html",
        "m-33-trust-and-governance.html",
        "m-34-architecture-reader-guide.html",
    ]:
      assert href in by_href, f"search index is missing {href}"

    assert by_href["walkthrough.html"]["section"] == "Operate CALIBER"
    assert "operator" in by_href["walkthrough.html"]["audience"]
    assert by_href["m-21-sdk-reference.html"]["doc_type"] == "reference"
    assert by_href["m-20-sdk-guide.html"]["doc_type"] == "tutorial"
    assert by_href["m-38-use-prompts.html"]["section"] == "Use CALIBER"
    assert by_href["m-02-prompts.html"]["section"] == "Architecture"

    assert "m-21-sdk-reference.html#reference" in by_href
    assert by_href["m-21-sdk-reference.html#reference"]["page_label"] == "SDK API reference"
    assert by_href["m-21-sdk-reference.html#reference"]["result_type"] == "anchor"
    assert "CaliberClient" in by_href["m-21-sdk-reference.html"]["symbols"]
    assert "/ajax-api/2.0/mlflow/caliber/openapi.json" in by_href["m-29-rest-api-reference.html"]["routes"]


def test_rest_api_reference_publishes_generated_route_inventory() -> None:
    html = (DOCS_SITE / "m-29-rest-api-reference.html").read_text(encoding="utf-8")
    payload = json.loads((DOCS_SITE / "search-index.json").read_text(encoding="utf-8"))
    by_href = {page["href"]: page for page in payload["pages"]}

    assert "Shared contract building blocks" in html
    assert "Security and scoping schemes" in html
    assert "SDK coverage by route family" in html
    assert "CaliberClient.openapi()" in html
    assert "client.prompts" in html
    assert "client.raw" in html
    assert "Current route inventory" in html
    assert "Jump by resource family" in html
    assert "GA routes index" in html
    assert '#prompts-prompts">Prompts' in html
    assert "OpenAPI JSON" in html
    assert "/ajax-api/2.0/mlflow/caliber/aria/plans/{plan_id}/execute" in html
    assert "/ajax-api/2.0/mlflow/caliber/system/webhook-dead-letters" in by_href[
        "m-29-rest-api-reference.html"
    ]["routes"]


def test_search_prefers_reference_pages_for_symbol_and_route_queries() -> None:
    symbol_results = _search_results("CaliberClient", limit=5)
    assert symbol_results, "CaliberClient returned no search results"
    assert symbol_results[0]["href"] == "m-21-sdk-reference.html"

    route_results = _search_results("/ajax-api/2.0/mlflow/caliber/openapi.json", limit=5)
    assert route_results, "REST API route query returned no search results"
    assert route_results[0]["href"] == "m-29-rest-api-reference.html"

    collateral_results = _search_results("presentation", limit=5)
    assert collateral_results, "presentation returned no search results"
    assert collateral_results[0]["href"] == "presentation.html"

    walkthrough_results = _search_results("walkthrough", limit=5)
    assert walkthrough_results, "walkthrough returned no search results"
    assert walkthrough_results[0]["href"] == "walkthrough.html"


def test_beta_sdk_page_is_visibly_labeled_beta() -> None:
    html = (DOCS_SITE / "m-22-sdk-beta.html").read_text(encoding="utf-8")
    assert 'doc-meta-chip-stability">BETA<' in html


def test_published_metadata_block_surfaces_prerequisites_on_generated_pages() -> None:
    guide = (DOCS_SITE / "m-20-sdk-guide.html").read_text(encoding="utf-8")
    api_reference = (DOCS_SITE / "m-29-rest-api-reference.html").read_text(encoding="utf-8")
    sdk_reference = (DOCS_SITE / "m-21-sdk-reference.html").read_text(encoding="utf-8")

    assert 'doc-meta-label">Prerequisites<' in guide
    assert "Python 3.10+" in guide
    assert 'doc-meta-label">Prerequisites<' in api_reference
    assert "CALIBER API integration question" in api_reference
    assert 'doc-meta-chip-type">Reference<' in sdk_reference
