/* Generated by build-docs.mjs — do not edit by hand. */
window.DOCS_NAV = [
  {
    "section": "Documentation",
    "links": [
      {
        "href": "index.html",
        "label": "Overview"
      }
    ]
  },
  {
    "section": "Platform",
    "links": [
      {
        "href": "m-00-layered-architecture.html",
        "label": "Layered architecture"
      },
      {
        "href": "m-01-platform.html",
        "label": "Platform"
      },
      {
        "href": "m-00-refinement-loop.html",
        "label": "The refinement loop"
      }
    ]
  },
  {
    "section": "Authoring",
    "links": [
      {
        "href": "m-02-prompts.html",
        "label": "Prompts"
      },
      {
        "href": "m-03-tools.html",
        "label": "Tools"
      },
      {
        "href": "m-04-skills.html",
        "label": "Skills"
      },
      {
        "href": "m-05-mcp.html",
        "label": "MCP servers"
      },
      {
        "href": "m-06-workflows.html",
        "label": "Workflows"
      },
      {
        "href": "m-06-workflows-components.html",
        "label": "Workflow components"
      }
    ]
  },
  {
    "section": "Data & knowledge",
    "links": [
      {
        "href": "m-07-object-store.html",
        "label": "Object store"
      },
      {
        "href": "m-08-knowledge-bases.html",
        "label": "Knowledge bases"
      }
    ]
  },
  {
    "section": "Quality & trust",
    "links": [
      {
        "href": "m-11-test-sets.html",
        "label": "Test sets"
      },
      {
        "href": "m-14-evaluation.html",
        "label": "Evaluation"
      },
      {
        "href": "m-15-calibration.html",
        "label": "Calibration"
      }
    ]
  },
  {
    "section": "Operations",
    "links": [
      {
        "href": "m-09-observability.html",
        "label": "Observability"
      },
      {
        "href": "m-10-gateways.html",
        "label": "Gateways"
      },
      {
        "href": "m-13-qa-plan.html",
        "label": "QA plan"
      },
      {
        "href": "m-19-runbook.html",
        "label": "Operations runbook"
      }
    ]
  },
  {
    "section": "Aria assistant",
    "links": [
      {
        "href": "m-12-assistant.html",
        "label": "Overview"
      }
    ]
  },
  {
    "section": "SDK",
    "links": [
      {
        "href": "m-20-sdk-guide.html",
        "label": "Python SDK guide"
      },
      {
        "href": "m-21-sdk-reference.html",
        "label": "Python SDK reference"
      },
      {
        "href": "m-22-sdk-beta.html",
        "label": "Beta and agentic surfaces"
      },
      {
        "href": "m-23-sdk-plugins.html",
        "label": "Writing a plugin"
      },
      {
        "href": "m-24-sdk-cli.html",
        "label": "CLI and async client"
      },
      {
        "href": "m-25-sdk-cookbooks.html",
        "label": "SDK cookbook implementations"
      }
    ]
  },
  {
    "section": "Strategy & roadmap",
    "links": [
      {
        "href": "m-17-competitive-analysis.html",
        "label": "Competitive analysis"
      },
      {
        "href": "m-18-roadmap.html",
        "label": "Roadmap"
      }
    ]
  },
  {
    "section": "Cookbooks",
    "links": [
      {
        "href": "m-16-cookbooks.html",
        "label": "All cookbooks"
      },
      {
        "href": "m-cookbook-01-intake-classifier.html",
        "label": "01 · Trustworthy Intake Classifier"
      },
      {
        "href": "m-cookbook-02-precision-skills.html",
        "label": "02 · Precision Skills"
      },
      {
        "href": "m-cookbook-03-policy-safe-tool.html",
        "label": "03 · Policy-Safe Decision Tool"
      },
      {
        "href": "m-cookbook-05-governed-mcp.html",
        "label": "05 · Governed Tool Connectivity (MCP)"
      },
      {
        "href": "m-cookbook-04-doc-to-json.html",
        "label": "04 · Document-to-JSON Pipeline"
      },
      {
        "href": "m-cookbook-06-grounded-knowledge.html",
        "label": "06 · Grounded Knowledge Assistant"
      },
      {
        "href": "m-cookbook-07-support-copilot.html",
        "label": "07 · Support Triage Copilot"
      },
      {
        "href": "m-cookbook-08-incident-copilot.html",
        "label": "08 · Incident Response Copilot"
      },
      {
        "href": "m-cookbook-09-self-healing-workflows.html",
        "label": "09 · Self-Healing Workflows"
      },
      {
        "href": "m-cookbook-16-observability-triage.html",
        "label": "16 · Production Observability & Triage"
      },
      {
        "href": "m-cookbook-10-trustworthy-evaluation.html",
        "label": "10 · Trustworthy Evaluation"
      },
      {
        "href": "m-cookbook-11-release-signoff.html",
        "label": "11 · Release Signoff Factory"
      },
      {
        "href": "m-cookbook-12-aria-eval-harness.html",
        "label": "12 · Aria: Evaluation Harness from Intent"
      },
      {
        "href": "m-cookbook-13-aria-review-queue.html",
        "label": "13 · Aria: Human-Review Queue from Intent"
      },
      {
        "href": "m-cookbook-14-aria-starter-kit.html",
        "label": "14 · Aria: Governance Starter Kit from Intent"
      },
      {
        "href": "m-cookbook-15-aria-triage-loop.html",
        "label": "15 · Aria: Triage & Recalibrate Loop"
      }
    ]
  },
  {
    "section": "Walkthrough",
    "links": [
      {
        "href": "walkthrough.html",
        "label": "Guided walkthrough"
      },
      {
        "href": "presentation.html",
        "label": "Presentation",
        "newtab": true
      }
    ]
  }
];
