"""Text measurement for the scene builders, from the diagram typeface itself.

``metrics.json`` is generated by ``gen_metrics.mjs`` from the same Latin Modern Sans
faces the renderer draws with, so a width computed here is the width that will be
rendered. Guessing instead -- which the first version of this code did, at roughly
0.52 em per character -- produces boxes that are subtly too narrow, and the only
symptom is text crossing a border in the output.
"""

from __future__ import annotations

import json
from pathlib import Path

_JSON = Path(__file__).resolve().parent / "metrics.json"

_data = json.loads(_JSON.read_text(encoding="utf-8")) if _JSON.exists() else None


def _style(bold: bool, italic: bool) -> str:
    if bold:
        return "bold"
    if italic:
        return "italic"
    return "regular"


def text_width(text: str, size: float, *, bold: bool = False,
               italic: bool = False) -> float:
    """The advance width of ``text`` at ``size`` points."""
    if _data is None:
        # A rough fallback keeps the builders usable before metrics are generated;
        # it is deliberately generous so a missing metrics.json shows up as boxes
        # that are too wide rather than as text that overflows.
        return len(text) * size * 0.60
    widths = _data["styles"][_style(bold, italic)]
    total = 0.0
    for ch in text:
        w = widths.get(str(ord(ch)))
        if w is None:
            raise ValueError(
                f"U+{ord(ch):04X} {ch!r} has no glyph in the diagram typeface; "
                f"it cannot be measured or rendered"
            )
        total += w
    return total * size
