"""Fake assistant engine — deterministic stubs for tests and demos.

The fake engine behaves like a real CALIBER copilot would at a coarse level: it
only enters the artifact-authoring flow when the user actually expresses an
intent to build something (an explicit ``artifact_type``, build keywords in the
message, or an authoring flow that is already in progress for the session).
Greetings and general questions get a conversational reply instead of an
unsolicited draft — so saying "hello" no longer starts building a tool.
"""

from __future__ import annotations

import re

from caliber.assistant.models import (
    ArtifactType,
    AssistantTurnRequest,
    AssistantTurnResult,
    ClarifyingQuestion,
    DraftDelta,
)

# Pre-built artifact skeletons per type.
_FAKE_ARTIFACTS: dict[str, dict[str, object]] = {
    "tool": {
        "name": "fake_tool",
        "description": "A fake tool generated by the assistant.",
        "source": 'def fake_tool(x: str) -> str:\n    """Return uppercased input."""\n    return x.upper()\n',
        "input_schema": {"type": "object", "properties": {"x": {"type": "string"}}},
        "output_schema": {"type": "object", "properties": {"result": {"type": "string"}}},
    },
    "skill": {
        "name": "fake_skill",
        "description": "A fake skill generated by the assistant.",
        "prompt": "You are a helpful assistant.",
        "metadata": {},
    },
    "prompt": {
        "name": "fake_prompt",
        "template": "Hello, {{name}}!",
        "variables": ["name"],
        "output_contract": {"type": "string"},
    },
    "workflow": {
        "name": "fake_workflow",
        "description": "A fake workflow generated by the assistant.",
        "manifest": {
            "version": "1.0",
            "steps": [
                {"id": "step_1", "tool": "fake_tool", "inputs": {"x": "hello"}},
            ],
        },
    },
    "mcp_server": {
        "name": "fake_mcp_server",
        "transport": "stdio",
        "command": "echo",
        "args": ["hello"],
    },
}

# Word-boundary match so casual text ("address", "additional") never looks like a
# build request, while real phrasing ("create a tool", "calibrate this prompt")
# does. Continuation turns are handled separately via the active step counter.
_BUILD_INTENT_RE = re.compile(
    r"\b("
    r"create|build|make|generate|design|implement|scaffold|author|draft|"
    r"calibrate|optimi[sz]e|refactor|"
    r"tool|skill|prompt|workflow|mcp|agent|dataset"
    r")\b",
    re.IGNORECASE,
)

_GREETING = (
    "Hi — I'm Aria, your CALIBER copilot. I can help you create and refine tools, "
    "skills, prompts, workflows, and MCP servers, then validate, test, and publish "
    "them through CALIBER's gates. What would you like to build or explore?"
)


def _has_build_intent(message: str) -> bool:
    return bool(_BUILD_INTENT_RE.search(message or ""))


class FakeAssistantEngine:
    """Deterministic engine for unit tests and local demos.

    Conversational by default. Once authoring begins for a session, the flow is:
    first authoring turn asks a clarifying question, the next produces a draft
    delta, and subsequent turns reply "done".
    """

    def __init__(self) -> None:
        # Per-session authoring progress; 0 means authoring has not started.
        self._steps: dict[str, int] = {}

    def run_turn(  # noqa: PLR0911
        self,
        request: AssistantTurnRequest,
        *,
        toolset: object | None = None,  # noqa: ARG002 — fake engine ignores tools
    ) -> AssistantTurnResult:
        artifact_type: ArtifactType = request.artifact_type or "tool"

        attachment_note = ""
        if request.attachments:
            names = ", ".join(str(a.get("name") or "?") for a in request.attachments)
            attachment_note = f" I can see {len(request.attachments)} attachment(s): {names}."

        # Steer / chat / plan never produce drafts and never advance authoring.
        if request.steer:
            return AssistantTurnResult(
                reply=f"(steering) Understood — adjusting course based on your latest input.{attachment_note}",
            )
        if request.mode == "chat":
            return AssistantTurnResult(
                reply=f"(chat) Happy to help.{attachment_note} What would you like to know?",
            )
        if request.mode == "plan":
            return AssistantTurnResult(
                reply=(
                    f"(plan) Here's how I'd approach building a {artifact_type}: "
                    f"1) clarify requirements, 2) draft the artifact, 3) validate and "
                    f"test, 4) publish.{attachment_note} Switch to Build mode when ready."
                ),
            )

        # Build mode: only author when there's a real signal — an explicit
        # artifact type, build intent in the message, or an authoring flow already
        # in progress. Otherwise, converse like an assistant.
        active = self._steps.get(request.session_id, 0)
        wants_authoring = (
            active > 0
            or request.artifact_type is not None
            or _has_build_intent(request.user_message)
        )
        if not wants_authoring:
            return AssistantTurnResult(reply=f"{_GREETING}{attachment_note}")

        step = active
        self._steps[request.session_id] = step + 1

        if step == 0:
            return AssistantTurnResult(
                reply=f"Happy to help you create a {artifact_type}. A couple of quick questions first.",
                questions=[
                    ClarifyingQuestion(
                        question=f"What should the {artifact_type} be named?",
                        field="name",
                    ),
                ],
            )

        if step == 1:
            skeleton = _FAKE_ARTIFACTS.get(artifact_type, _FAKE_ARTIFACTS["tool"])
            title = skeleton.get("name")
            summary = skeleton.get("description")
            return AssistantTurnResult(
                reply=f"I've created a draft {artifact_type} for you. Please review it.",
                draft_deltas=[
                    DraftDelta(
                        artifact_type=artifact_type,
                        title=title if isinstance(title, str) else f"fake_{artifact_type}",
                        summary=summary if isinstance(summary, str) else "",
                        spec={"assumptions": ["Generated by FakeAssistantEngine"]},
                        artifact=skeleton,
                    ),
                ],
            )

        return AssistantTurnResult(
            reply="All done! You can validate, test, and publish the draft when ready.",
            done=True,
        )
