"""Generated by caliber-workflow-compiler. Do not edit by hand.

workflow_id: multi_agent_wf
version: 1
manifest_hash: c4ed4d884854cca251af90a74427fe2412e72552ad0c8192dabf8379dd2c6335
compiler_version: 0.1.0
"""

from typing import Any

from agents import Agent, RunConfig, Runner, handoff
import mlflow

from caliber.workflows.guardrails import enforce_guardrails
from caliber.workflows.runtime import run_with_caliber_context, workflow_model
from caliber.workflows.runtime import bind_exported_tool
from caliber.workflows.tools import ToolRegistryEntry

def _build_agent_graph(*, config: Any | None = None):
    # Tool bindings (resolved from the CALIBER tool registry).
    get_order = bind_exported_tool(ToolRegistryEntry(**{"allow_in_preview": False, "backend_config": None, "callable_name": "<lambda>", "execution_backend": "python_callable", "input_schema": None, "module_path": "<in-memory>", "name": "get_order", "output_schema": None, "requires_approval": False, "secret_refs": (), "side_effect_level": "read", "version": "1.0"}), config=config)
    lookup_policy = bind_exported_tool(ToolRegistryEntry(**{"allow_in_preview": False, "backend_config": None, "callable_name": "<lambda>", "execution_backend": "python_callable", "input_schema": None, "module_path": "<in-memory>", "name": "lookup_policy", "output_schema": None, "requires_approval": False, "secret_refs": (), "side_effect_level": "read", "version": "1.0"}), config=config)
    # node: billing
    billing = Agent(
        name="billing-agent",
        model=workflow_model("billing"),
        instructions="Handle billing.",
        tools=[get_order],
        handoffs=[],
    )
    # node: agent
    agent = Agent(
        name="test-agent",
        model=workflow_model("agent"),
        instructions="You are helpful.",
        tools=[lookup_policy],
        handoffs=[handoff(billing, tool_description_override="billing issues")],
    )
    return agent

def run(input_text: str, *, session_id: str | None = None, config: Any | None = None):
    with run_with_caliber_context(
        workflow_id="multi_agent_wf",
        workflow_version="1",
        entry_node_id="agent",
        compiler_version="0.1.0",
        manifest_hash="c4ed4d884854cca251af90a74427fe2412e72552ad0c8192dabf8379dd2c6335",
        default_model_ref="CALIBER_WORKFLOW_DEFAULT_MODEL",
        extra_tags={},
        session_id=session_id,
    ):
        entry_agent = _build_agent_graph(config=config)
        result = Runner.run_sync(entry_agent, input_text, run_config=RunConfig(tracing_disabled=True))
        return result.final_output
