"""Generated by caliber-workflow-compiler. Do not edit by hand.

workflow_id: single_agent_wf
version: 1
manifest_hash: 0522972e41d58cee5977a855b423a99c8510bf47c171398c598a6dec95fa7b89
compiler_version: 0.1.0
"""

from agents import Agent, Runner, handoff
import mlflow

from caliber.workflows.guardrails import enforce_guardrails
from caliber.workflows.runtime import run_with_caliber_context, workflow_model
from caliber.workflows.runtime import bind_exported_tool
from caliber.workflows.tools import ToolRegistryEntry

# node: agent
agent = Agent(
    name="test-agent",
    model=workflow_model("agent"),
    instructions="You are helpful.",
    tools=[],
    handoffs=[],
)

def run(input_text: str, *, session_id: str | None = None):
    with run_with_caliber_context(
        workflow_id="single_agent_wf",
        workflow_version="1",
        entry_node_id="agent",
        compiler_version="0.1.0",
        manifest_hash="0522972e41d58cee5977a855b423a99c8510bf47c171398c598a6dec95fa7b89",
        default_model_ref="CALIBER_WORKFLOW_DEFAULT_MODEL",
        extra_tags={},
        session_id=session_id,
    ):
        result = Runner.run_sync(agent, input_text)
        return result.final_output
